---
apiVersion: v1
kind: Pod
metadata:
  name: label-demo1
  labels:
    environment: developer
    team: infra-ops
    project: qt-ecommerce
  annotations:
    commit-id: 3190dd9e231b92f07da29e052a0fbc812ed8c999
    jira-issue: "https://jira.qualtitythought.in/issue/OP-25"
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
          protocol: TCP